<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Successfull_btnOK</name>
   <tag></tag>
   <elementGuidId>866b87a0-fffb-44bc-97d5-be2a9d5be052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-17']/nz-modal-container/div/div/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-modal-footer.ng-tns-c2582198243-486.ng-star-inserted > button.ant-btn.ant-btn-primary.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>940d2e0a-b3f7-4bc3-be3a-1b20aa5de283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ng-star-inserted</value>
      <webElementGuid>97824f8f-e305-4618-bac2-cdcc3ce48e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d92fd7d2-1709-42f3-b161-7e85106034d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-danger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0e11c81-ca33-4093-b1ac-3f2e504fa197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ea7661b-e125-4222-8e90-8a3ee6bab6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ab2f8bd-9734-4288-8925-0bb5426bfb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> OK </value>
      <webElementGuid>a667e9fe-bc02-444d-a409-3bf9e1566ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-17&quot;)/nz-modal-container[@class=&quot;ng-tns-c2582198243-486 ng-trigger ng-trigger-modalContainer ng-star-inserted ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal ng-tns-c2582198243-486&quot;]/div[@class=&quot;ant-modal-content ng-tns-c2582198243-486&quot;]/div[@class=&quot;ant-modal-footer ng-tns-c2582198243-486 ng-star-inserted&quot;]/button[@class=&quot;ant-btn ant-btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>286b6dcc-690c-44c0-8f1e-110bc992ddbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-17']/nz-modal-container/div/div/div[3]/button[2]</value>
      <webElementGuid>43e2fb4d-a4cb-473f-b010-7cb74c199e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>fe709913-90dd-4c04-a78c-39eee4432a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successful'])[1]/following::button[2]</value>
      <webElementGuid>9af40975-08cf-4bb3-8709-df942d289eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>7506c309-3c14-4f9c-aa5c-06c8cb7f2251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' OK ' or . = ' OK ')]</value>
      <webElementGuid>1827ea66-3153-4700-8b6c-ee681e93e513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
