<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateRFI_ServiceInfo_AdditionalInfo_txtPercentage SeaFCL</name>
   <tag></tag>
   <elementGuidId>80776cc3-fa76-4f71-86b1-ebfc4d2daf41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ng-tns-c630436078-309.ng-untouched.ng-pristine.ng-invalid.ant-input-stepperless</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[.//th[normalize-space()='Mode of Transports']]//tr[.//td[normalize-space()='${ModeOfTransport}']]/td[3]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;100%&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72935754-7703-457e-9652-fe96f93b96ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mainModeInput</value>
      <webElementGuid>0459efc8-f70c-48a6-949c-e341d1926b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3808fccc-3221-40f1-9bcb-31f2cfe22447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>31432c72-05ab-4f57-b042-f58132c03dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ng-tns-c630436078-309 ng-untouched ng-pristine ng-invalid ant-input-stepperless</value>
      <webElementGuid>686f9cca-2bea-4034-b785-9a40d6e3929a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>mainModeInput</value>
      <webElementGuid>8628d22b-9ee8-4f05-8db6-863412e911fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ad09e2f-42fa-4310-ae88-bd526b6d0019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>4ccf0a73-2a9f-4a1c-9a4e-5dee4f3f73da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3a8b4bee-85dc-449f-a55b-5ab2c2bbee44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout layout&quot;]/nz-content[@class=&quot;outer-content ant-layout-content ng-star-inserted&quot;]/div[@class=&quot;inner-content&quot;]/app-rfi-create[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-create&quot;]/div[@class=&quot;steps-content no-bg&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-abs&quot;]/nz-tabset[@class=&quot;ant-tabs full-tab ant-tabs-top ant-tabs-default&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-top ant-tabs-content-animated&quot;]/div[@class=&quot;ant-tabs-tabpane ng-star-inserted ant-tabs-tabpane-active&quot;]/app-additional-info[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ant-form ng-untouched ng-pristine ng-invalid ant-form-horizontal&quot;]/div[@class=&quot;box-additional-info&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/nz-card[@class=&quot;ant-card card-border ant-card-bordered ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ant-card-body&quot;]/nz-table[@class=&quot;ant-table-wrapper ng-star-inserted&quot;]/nz-spin[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container ng-star-inserted&quot;]/div[@class=&quot;ant-table&quot;]/nz-table-inner-default[@class=&quot;ant-table-container ng-star-inserted&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody ng-star-inserted&quot;]/tr[@class=&quot;ng-untouched ng-pristine ng-invalid ant-table-row ng-star-inserted&quot;]/td[@class=&quot;ant-table-cell&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row mb-0&quot;]/nz-form-control[@class=&quot;ant-form-item-control ng-tns-c630436078-309 ant-col ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c630436078-309&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c630436078-309&quot;]/input[@class=&quot;ant-input ng-tns-c630436078-309 ng-untouched ng-pristine ng-invalid ant-input-stepperless&quot;]</value>
      <webElementGuid>13c287bb-cf39-405d-bae4-744f9935d14a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[3]/nz-form-item/nz-form-control/div/div/input</value>
      <webElementGuid>d13cbe4a-e175-4dae-b286-3201d20e8e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '100%']</value>
      <webElementGuid>767787d4-ea12-48f0-b7a3-ba24a61ece48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
