<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CommoditySpecification_chkCommoditySpecification</name>
   <tag></tag>
   <elementGuidId>64f180d2-db07-407e-8c82-c486bcc1199a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[.//span[text()='${commoditySpecification }']]//input[@type='checkbox']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-checkbox-input.ng-pristine.ng-valid.ng-touched</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;General&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ecfd628-eb8f-4b44-b6e4-0621d2acfeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fef29cca-e58d-4a13-8aa1-955e2db0b1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input ng-pristine ng-valid ng-touched</value>
      <webElementGuid>85a8496a-b62e-4dc3-a774-f3184f3a1df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ffe3ae7a-cc72-44a0-ab21-fc5215654a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3f4c656-cf41-4e8c-8146-44b0f0fcedb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout layout&quot;]/nz-content[@class=&quot;outer-content ant-layout-content ng-star-inserted&quot;]/div[@class=&quot;inner-content&quot;]/app-rfi-create[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-create&quot;]/div[@class=&quot;steps-content no-bg&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-abs&quot;]/nz-tabset[@class=&quot;ant-tabs full-tab ant-tabs-top ant-tabs-default&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-top ant-tabs-content-animated&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/app-capacity-services[@class=&quot;ng-star-inserted&quot;]/nz-tabset[@class=&quot;ant-tabs tab-service ant-tabs-left ant-tabs-default fixed&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-left&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid ng-submitted&quot;]/nz-collapse[@class=&quot;ant-collapse ant-collapse-icon-position-left&quot;]/nz-collapse-panel[@class=&quot;ant-collapse-item ng-tns-c4187469874-139 ng-star-inserted ng-touched ng-dirty ant-collapse-item-active ng-valid&quot;]/div[@class=&quot;ant-collapse-content ng-tns-c4187469874-139 ng-trigger ng-trigger-collapseMotion ant-collapse-content-active&quot;]/div[@class=&quot;ant-collapse-content-box ng-tns-c4187469874-139&quot;]/app-volume-commodity[@class=&quot;ng-tns-c4187469874-139&quot;]/form[@class=&quot;ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;ant-row mt-24 row-volumn-commondity ant-row-space-between&quot;]/div[@class=&quot;full-with-tablet ant-col ant-col-12&quot;]/div[@class=&quot;bg-table&quot;]/div[@class=&quot;ant-row ng-dirty ant-row-space-between ng-touched ng-invalid&quot;]/nz-form-control[@class=&quot;ant-form-item-control ant-row ng-tns-c630436078-146 ant-col ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c630436078-146&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c630436078-146&quot;]/nz-checkbox-wrapper[@class=&quot;ant-checkbox-group ant-row group-scope ng-tns-c630436078-146&quot;]/div[@class=&quot;gutter-row ant-col ant-col-12 ng-dirty ng-valid ng-star-inserted ng-touched&quot;]/label[@class=&quot;ant-checkbox-wrapper ant-checkbox-wrapper-in-form-item ng-dirty ng-valid ng-star-inserted ng-touched cdk-focused cdk-keyboard-focused&quot;]/span[@class=&quot;ant-checkbox&quot;]/input[@class=&quot;ant-checkbox-input ng-pristine ng-valid ng-touched&quot;]</value>
      <webElementGuid>89e4ab8f-91c3-42e0-a767-03baadbf8d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>fffcdd2c-7350-40f6-9300-902a94395055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/span/input</value>
      <webElementGuid>ee279246-b3ce-4ff6-bd43-cf2a0101fa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>4391d688-acd6-4a8e-8083-700ff4facfe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
