<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Destination_itm_Country</name>
   <tag></tag>
   <elementGuidId>36b4d523-ace6-45e1-b1fc-5422dfe00185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ant-select-item-option-content'][normalize-space()='${DestinationCountry}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nz-select-top-control.ant-select-selector.ng-tns-c69490912-281 > nz-select-item.ant-select-selection-item.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Australia&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nz-select-item</value>
      <webElementGuid>ef3c3afe-4b1a-4fb9-bae9-c9eeb06d7b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item ng-star-inserted</value>
      <webElementGuid>614b6af6-32b9-4481-8321-93ce687f0895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-deletable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27cbfeca-f5e2-4ce6-a9e1-5ed7bd604c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fc06f87-e4f0-443f-a96a-0b1c7b60bc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-remove-icon</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f71064c2-1a07-4a6b-aecb-aa5600f5fd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-label</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>0576f74a-7024-4738-8023-c230055aef1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-content-template-outlet-context</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2c71f276-c3dd-4197-8b5c-fa3936c48664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>5a824e77-ca00-45ab-9f75-05550d2cf568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>7a693699-ff2f-43f5-8a59-94a8151a26be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout layout&quot;]/nz-content[@class=&quot;outer-content ant-layout-content ng-star-inserted&quot;]/div[@class=&quot;inner-content&quot;]/app-rfi-create[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-create&quot;]/div[@class=&quot;steps-content no-bg&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-abs&quot;]/nz-tabset[@class=&quot;ant-tabs full-tab ant-tabs-top ant-tabs-default&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-top ant-tabs-content-animated&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/app-capacity-services[@class=&quot;ng-star-inserted&quot;]/nz-tabset[@class=&quot;ant-tabs tab-service ant-tabs-left ant-tabs-default fixed&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-left&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/nz-collapse[@class=&quot;ant-collapse ant-collapse-icon-position-left&quot;]/nz-collapse-panel[@class=&quot;ant-collapse-item ng-tns-c4187469874-261 ant-collapse-item-active ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;ant-collapse-content ng-tns-c4187469874-261 ant-collapse-content-active ng-trigger ng-trigger-collapseMotion&quot;]/div[@class=&quot;ant-collapse-content-box ng-tns-c4187469874-261&quot;]/div[@class=&quot;bg-table ng-tns-c4187469874-261&quot;]/div[@class=&quot;ant-row ant-row-space-between&quot;]/div[@class=&quot;ant-col ant-col-12 ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row ant-form-item-has-success&quot;]/nz-form-control[@class=&quot;ant-form-item-control ng-tns-c630436078-280 ant-col ant-col-24 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c630436078-280&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c630436078-280&quot;]/nz-select[@class=&quot;ant-select ng-tns-c69490912-281 ng-tns-c630436078-280 ant-select-in-form-item ant-select-show-arrow ant-select-show-search ant-select-single ng-star-inserted ng-touched ant-select-status-success ng-dirty ng-valid&quot;]/nz-select-top-control[@class=&quot;ant-select-selector ng-tns-c69490912-281&quot;]/nz-select-item[@class=&quot;ant-select-selection-item ng-star-inserted&quot;]</value>
      <webElementGuid>082c50e9-0d38-40d1-87aa-4a8dcfdccf7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::nz-select-item[1]</value>
      <webElementGuid>88851192-437a-465d-8fb7-50919a0bff74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination'])[1]/following::nz-select-item[1]</value>
      <webElementGuid>2316dd43-02ee-4143-b5aa-4b83cfa9011e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code - Seaport - State'])[1]/preceding::nz-select-item[1]</value>
      <webElementGuid>75d09b59-919a-443c-a509-b55129d43f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Code - Seaport - State'])[1]/preceding::nz-select-item[1]</value>
      <webElementGuid>438c0088-808b-4338-a15e-9689a874b07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Australia']/parent::*</value>
      <webElementGuid>29bd6820-8766-46a3-b993-3b7a0d99bd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/nz-form-item/nz-form-control/div/div/nz-select/nz-select-top-control/nz-select-item</value>
      <webElementGuid>4bdecc3e-1d3c-43b8-9a9b-e4a0c6fd8e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nz-select-item[@title = 'Australia' and (text() = 'Australia' or . = 'Australia')]</value>
      <webElementGuid>bf3dd5fd-f032-4919-b18b-3048fab682ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
