<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Destination_itm_CodeSea</name>
   <tag></tag>
   <elementGuidId>166a41f2-c7d0-469b-8b67-db165c38bde2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nz-option-item[contains(@title,'${DestinationProvince}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vela-select-multiple__option-item.ng-star-inserted.vela-select-multiple__option-item--selected > div.vela-select-multiple__option-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nz-option-item >> internal:has-text=&quot;VNHPH - Hai Phong - Hai Phong&quot;i >> div >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cca34f9-6eb7-43c7-9d09-e384e8adfbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vela-select-multiple__option-overlay</value>
      <webElementGuid>36965767-ae61-4574-a9ba-496673a5578c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/nz-option-container[@class=&quot;ant-select-dropdown ng-tns-c69490912-164 ant-select-dropdown-placement-bottomLeft ng-trigger ng-trigger-slideMotion ng-star-inserted&quot;]/div[1]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport cdk-virtual-scrollable cdk-virtual-scroll-orientation-vertical&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/nz-option-item[@class=&quot;ant-select-item ant-select-item-option ng-star-inserted ant-select-item-option-selected ant-select-item-option-active&quot;]/div[@class=&quot;ant-select-item-option-content&quot;]/div[@class=&quot;vela-select-multiple__option-item ng-star-inserted vela-select-multiple__option-item--selected&quot;]/div[@class=&quot;vela-select-multiple__option-overlay&quot;]</value>
      <webElementGuid>e010291c-aade-4dda-8ab1-186824919e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/nz-option-container/div/cdk-virtual-scroll-viewport/div/nz-option-item[2]/div/div/div</value>
      <webElementGuid>44af8d84-dd21-4056-a7e1-0ecd93f87fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-option-item[2]/div/div/div</value>
      <webElementGuid>443331a4-7d4f-4a43-b43c-0f0970394560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
