<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Origin_itm_Country</name>
   <tag></tag>
   <elementGuidId>f46b9eb1-7036-48e9-abe3-5031f5dcc3e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ant-select-item-option-content'][normalize-space()='${OriginCountry}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nz-select-top-control.ant-select-selector.ng-tns-c69490912-281 > nz-select-item.ant-select-selection-item.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Australia&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nz-select-item</value>
      <webElementGuid>0768f9e2-3a9f-4186-bd5c-1be91054c71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item ng-star-inserted</value>
      <webElementGuid>5df57f65-852c-4581-a2c3-70dc4620ea54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-deletable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>45b8ee99-fee7-4b0f-817d-1f3cee0fa744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b910df1b-832f-456f-9432-77d483357d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-remove-icon</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>790bdd2b-0937-4ff1-b876-01b02969a0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-label</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>c7933a63-4880-4b85-8dc9-0173a6901fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-content-template-outlet-context</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9ddba175-d889-43ec-919b-dbd136508e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>3a852854-61b4-4679-9a54-729349a85dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>8be0a6fb-845c-4005-aafa-12532242e20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout layout&quot;]/nz-content[@class=&quot;outer-content ant-layout-content ng-star-inserted&quot;]/div[@class=&quot;inner-content&quot;]/app-rfi-create[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-create&quot;]/div[@class=&quot;steps-content no-bg&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-abs&quot;]/nz-tabset[@class=&quot;ant-tabs full-tab ant-tabs-top ant-tabs-default&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-top ant-tabs-content-animated&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/app-capacity-services[@class=&quot;ng-star-inserted&quot;]/nz-tabset[@class=&quot;ant-tabs tab-service ant-tabs-left ant-tabs-default fixed&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-left&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/nz-collapse[@class=&quot;ant-collapse ant-collapse-icon-position-left&quot;]/nz-collapse-panel[@class=&quot;ant-collapse-item ng-tns-c4187469874-261 ant-collapse-item-active ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;ant-collapse-content ng-tns-c4187469874-261 ant-collapse-content-active ng-trigger ng-trigger-collapseMotion&quot;]/div[@class=&quot;ant-collapse-content-box ng-tns-c4187469874-261&quot;]/div[@class=&quot;bg-table ng-tns-c4187469874-261&quot;]/div[@class=&quot;ant-row ant-row-space-between&quot;]/div[@class=&quot;ant-col ant-col-12 ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row ant-form-item-has-success&quot;]/nz-form-control[@class=&quot;ant-form-item-control ng-tns-c630436078-280 ant-col ant-col-24 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c630436078-280&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c630436078-280&quot;]/nz-select[@class=&quot;ant-select ng-tns-c69490912-281 ng-tns-c630436078-280 ant-select-in-form-item ant-select-show-arrow ant-select-show-search ant-select-single ng-star-inserted ng-touched ant-select-status-success ng-dirty ng-valid&quot;]/nz-select-top-control[@class=&quot;ant-select-selector ng-tns-c69490912-281&quot;]/nz-select-item[@class=&quot;ant-select-selection-item ng-star-inserted&quot;]</value>
      <webElementGuid>8779ec91-476c-4615-a6f1-be6c027f064d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::nz-select-item[1]</value>
      <webElementGuid>aad13a1f-a59d-4550-9540-45bc70c52263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination'])[1]/following::nz-select-item[1]</value>
      <webElementGuid>5f7dcdb1-9398-4088-9630-b09a42734797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code - Seaport - State'])[1]/preceding::nz-select-item[1]</value>
      <webElementGuid>3f9801d4-78ce-4cac-96d1-59840cb2a5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Code - Seaport - State'])[1]/preceding::nz-select-item[1]</value>
      <webElementGuid>2c8b2683-aa89-4427-8729-1f31570f7d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Australia']/parent::*</value>
      <webElementGuid>43dc17b8-5cba-4298-954a-f498deea5377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/nz-form-item/nz-form-control/div/div/nz-select/nz-select-top-control/nz-select-item</value>
      <webElementGuid>833279ee-6633-41f4-ae07-a1967d1581c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nz-select-item[@title = 'Australia' and (text() = 'Australia' or . = 'Australia')]</value>
      <webElementGuid>5142f01d-58d3-4fc6-9be1-07c0eb812016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
