<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Origin_ddl_CodeSea</name>
   <tag></tag>
   <elementGuidId>ed1cf3b1-4acb-43fe-8ec2-f9bf6413488b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ant-row ant-row-space-between']//div[@class='ant-col ant-col-12 ng-star-inserted'][1]//nz-select-top-control[starts-with(@class,'ant-select-selector') and .//*[contains(normalize-space(),'Select Code - Seaport')]]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nz-select.ant-select.ng-tns-c69490912-161.ant-select-in-form-item.ant-select-show-arrow.ant-select-show-search.ant-select-allow-clear.ant-select-multiple.ng-untouched.ng-pristine.ng-valid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '  Select Code - Seaport - State ' or . = '  Select Code - Seaport - State ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nz-select >> internal:has-text=&quot;Select Code - Seaport - State&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nzmode</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>42c040f7-a207-494f-b9a8-475d36064594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nzdropdownclassname</name>
      <type>Main</type>
      <value>vela-select-multiple__dropdown</value>
      <webElementGuid>ac6bd51a-726a-4661-9fdd-320dd2e41d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select ng-tns-c69490912-161 ant-select-in-form-item ant-select-show-arrow ant-select-show-search ant-select-allow-clear ant-select-multiple ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>70da6577-a974-41c8-b562-3f2e39564dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-mode</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>2ae6ff14-6822-4b4a-b850-139fa2fa5727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-dropdown-class-name</name>
      <type>Main</type>
      <value>vela-select-multiple__dropdown</value>
      <webElementGuid>ddd86e79-7ac3-4cee-afcd-490e4a21deea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-option-height-px</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>14512ac0-d0d5-4771-99cc-e29e788cb16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-show-arrow</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ffb0702-cd27-4b6c-ac56-36eab6f051d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-size</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ff4119f7-d885-4957-b5a0-e47cd6368bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-allow-clear</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c76a8d5e-6a38-49f8-8355-809b287b3e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-custom-template</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>a61857e7-73b4-481d-9fab-eacce618c280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-remove-icon</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d01064e0-821c-44b4-a68b-dcfad9c887bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-clear-icon</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>e7f2cdff-ca47-4bd7-9ae9-40d34fbe7192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-place-holder</name>
      <type>Main</type>
      <value>Select Code - Seaport - State</value>
      <webElementGuid>537f3323-7de7-4e49-b474-dcc1c7d53129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-option-overflow-size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>e82524df-4767-4733-a07d-15d4df5bdfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-max-tag-count</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9309443-669d-4f55-a52a-b1bf670f8718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5766c713-4cbc-4669-a6ea-13e9c0590f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-max-tag-placeholder</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>3e145fbe-cd06-41fc-9d3a-ce7701971c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nz-open</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2cbc7c4-ce99-42b5-8a60-360ab17b7c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-compare-with</name>
      <type>Main</type>
      <value>(o1, o2) => {
      if (typeof</value>
      <webElementGuid>ef97a3b5-c5ec-4960-8c83-de72a1a931fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Select Code - Seaport - State </value>
      <webElementGuid>7447c19c-866a-44b9-b377-2b8abda8cc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout layout&quot;]/nz-content[@class=&quot;outer-content ant-layout-content ng-star-inserted&quot;]/div[@class=&quot;inner-content&quot;]/app-rfi-create[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-create&quot;]/div[@class=&quot;steps-content no-bg&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-abs&quot;]/nz-tabset[@class=&quot;ant-tabs full-tab ant-tabs-top ant-tabs-default&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-top ant-tabs-content-animated&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/app-capacity-services[@class=&quot;ng-star-inserted&quot;]/nz-tabset[@class=&quot;ant-tabs tab-service ant-tabs-left ant-tabs-default&quot;]/div[@class=&quot;ant-tabs-content-holder&quot;]/div[@class=&quot;ant-tabs-content ant-tabs-content-left&quot;]/div[@class=&quot;ant-tabs-tabpane ant-tabs-tabpane-active ng-star-inserted&quot;]/form[@class=&quot;ng-star-inserted ng-invalid ng-touched ng-dirty&quot;]/nz-collapse[@class=&quot;ant-collapse ant-collapse-icon-position-left&quot;]/nz-collapse-panel[@class=&quot;ant-collapse-item ng-tns-c4187469874-139 ant-collapse-item-active ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;ant-collapse-content ng-tns-c4187469874-139 ant-collapse-content-active ng-trigger ng-trigger-collapseMotion&quot;]/div[@class=&quot;ant-collapse-content-box ng-tns-c4187469874-139&quot;]/div[@class=&quot;bg-table ng-tns-c4187469874-139&quot;]/div[@class=&quot;ant-row ant-row-space-between&quot;]/div[@class=&quot;ant-col ant-col-12 ng-star-inserted&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row&quot;]/nz-form-control[@class=&quot;ant-form-item-control ng-tns-c630436078-160 ant-col ant-col-24 ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c630436078-160&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c630436078-160&quot;]/vela-select-multiple[@class=&quot;ng-tns-c630436078-160 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;vela-select-multiple&quot;]/nz-select[@class=&quot;ant-select ng-tns-c69490912-161 ant-select-in-form-item ant-select-show-arrow ant-select-show-search ant-select-allow-clear ant-select-multiple ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>7ec64a86-6db7-4888-b65e-f2fd9ccc6e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1742a9f5-9bda-4c70-b50e-57bf5557055f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code - Seaport - State'])[1]/following::nz-select[1]</value>
      <webElementGuid>8d1574c7-3307-4199-9b8d-1a1e825adb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Origin Country'])[1]/following::nz-select[1]</value>
      <webElementGuid>dbeeea7d-2737-4209-9c2e-d512992b4f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[2]/preceding::nz-select[1]</value>
      <webElementGuid>6e996a36-9408-4ea1-9cdc-c0a2e4efd658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//vela-select-multiple/div/nz-select</value>
      <webElementGuid>8e197d9b-d4d0-4322-b2e2-2efa88c464e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nz-select[(text() = '  Select Code - Seaport - State ' or . = '  Select Code - Seaport - State ')]</value>
      <webElementGuid>d8f81ebd-ea62-4aff-ade7-36a5aad72d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
